multichat/chat/urls.py
from django.urls import path
from chat import views

urlpatterns = [
    path('room/list/', views.Rooms.as_view(), name='room'),
    path('room/detail/<int:pk>/', views.RoomDetailView.as_view(),name='room_detail'),
    path('room/status/requeste/', views.MemberPAgeRequestAPIView.as_view(),
         name='member_room_request'
         ),
    path('room/chatting/', views.ChattingRooms.as_view(), name='room_chatting'),
    path('owner/dashboard/', views.OwnerDashboard.as_view(), name='owner_dashboard'),
    path('room/owner/<int:pk>/create/admin/page/', 
    	views.CreatePageAdminView.as_view(),name='create_room_admin'),
    path('room/admin/dashboard/', views.AdminDashboardView.as_view(),
    	 name='admin_dashboard'),
    path('room/admin/dashboard/', views.MemberPageRequestApproveAPIView.as_view(),
    	 name='member_request_approve'),





]

multichat/multichat/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from chat.views import IndexView
from common import views

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('accounts/login/', login),
    path('accounts/logout/', logout),
    path('admin/', admin.site.urls),
    path("register/", views.RegisterView.as_view(), name="register"),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),


]

multichat/templates/rooms/admin_dashboard.html
{% extends "base.html" %}

{% block title %}Rooms{% endblock %}
{% block header_text %}Room List{% endblock %}

{% block content %}
{% for room in room_detail.room.all %}
           <button><li class="room-link" data-room-id="{{ room.id }}">Chat &nbsp;{{ room }}</li></button>
{% endfor %}
 <div id="chats">
    </div>
<br>
<br>
<br>
<div>all members</div>
<br>
<br>
<table>
    <tr>
        <th>id</th>
        <th>member name</th>
        <th>type</th>
        <th>action</th>
        <th>Chat with member personally</th>
    </tr>

    {% for user in room_detail.user.all %}
    <tr>
        <td id=user_id value="{{user.id}}">{{user.id}}</td>
        <td>{{user.username}}</td>
        <td>{{user.user_profile.type}}</td>
        <td><button class="confirm_btn">Accept Request</button>
</td>
        <td><button>chat</button></td>
    </tr>

    {% endfor %}

</table>
</div>
{% endblock %}

{% block extra_body %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);
            var socket = new ReconnectingWebSocket(ws_path);

            // Handle incoming messages
            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("li.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    socket.send(JSON.stringify({
                        "command": "leave",
                        "room": roomId
                    }));
                } else {
                    // Join room
                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));
                }
            });

            // Helpful debugging
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $('.confirm_btn').on ('click', function (){
        console.log("________________coming_______________");
        $.post("{% url 'chat:member_request_approve' %}", {
            console.log("________________________________");
            user_id: document.getElementById('user_id').value,
            csrfmiddlewaretoken: '{{ csrf_token }}',
        },function(result, status){
                if (result.status == 'requested') {
                    $('.confirmation-btn').html('Your Request is Submited!');
                    $('.confirm_btn').hide();
                }
                });

    });


</script>
{% endblock %}

multichat/templates/rooms/chating_room.html
{% extends "base.html" %}

{% block title %}MultiChat Example{% endblock %}
{% block header_text %}MultiChat Example{% endblock %}

{% block content %}

    <ul class="rooms">
        {% for room in rooms %}
            <li class="room-link" data-room-id="{{ room.id }}">{{ room }}</li>
        {% empty %}
            <p class="empty">No chat rooms defined. Maybe make some in the <a href="{% url 'admin:index' %}">admin</a>?</p>
        {% endfor %}
    </ul>

    <div id="chats">
    </div>

{% endblock %}


{% block extra_body %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);
            var socket = new ReconnectingWebSocket(ws_path);

            // Handle incoming messages
            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("li.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    socket.send(JSON.stringify({
                        "command": "leave",
                        "room": roomId
                    }));
                } else {
                    // Join room
                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));
                }
            });

            // Helpful debugging
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
{% endblock %}

multichat/templates/rooms/owner_dashboard.html
{% extends "base.html" %}

{% block title %}Rooms{% endblock %}
{% block header_text %}Room List{% endblock %}

{% block content %}
<h1>Owner Dashboard</h1>
<table class="table align-items-center table-striped table-bordered table-hover">
    <h1>Rooms</h1>
    <thead class="thead-dark">
    <tr>
        <th>Rooms Id</th>
        <th>Name</th>
        <th></th>
        <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    {% for room in rooms %}
        <tr>
            <td>{{room.id|stringformat:"03d"}}</td>
            <td>{{room.title|title}}</td>
            <td></td>
            <td class="text-center">
            <button><li class="room-link" data-room-id="{{ room.id }}">Chat</li></button>
            <button><a href="{% url 'chat:create_room_admin' pk=room.id %}">Crete page admin</a></button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
 <div id="chats">
    </div>


<table class="table align-items-center table-striped table-bordered table-hover">
    <h1>Users</h1>
    <thead class="thead-dark">
    <tr>
        <th>User Id</th>
        <th>Username</th>
        <th></th>
        <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    {% for user in members %}
        <tr>
            <td>{{user.id|stringformat:"03d"}}</td>
            <td>{{user.username|title}}</td>
            <td></td>
            <td class="text-center">
                <a href=""><button>Chat</button></a>&nbsp;
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block extra_body %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);
            var socket = new ReconnectingWebSocket(ws_path);

            // Handle incoming messages
            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("li.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    socket.send(JSON.stringify({
                        "command": "leave",
                        "room": roomId
                    }));
                } else {
                    // Join room
                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));
                }
            });

            // Helpful debugging
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
{% endblock %}

multichat/templates/rooms/room_detail.html
{% extends "base.html" %}

{% block title %}Rooms{% endblock %}
{% block header_text %}Room List{% endblock %}

{% block content %}
<h1>{{room.title}}</h1>
<h2>{{room.description}}</h2>
<div class="confirmation-btn"></div>

{% if room_detail.status == 'requested' %}
<div style="color:red;">Your Request was send Successfully </div>
{% elif room_detail.status == 'approved' %}
<div style="color: blue;"> your request is approved by  admin</div>
{% else %}
<button class="confirm_btn">Send Request</button>
{% endif %}
{% if room_detail.status == 'approved' %}
<button class="room-link" data-room-id="{{ room.id }}">Chat</button>
<div>all members
<table>
    <tr>
    <th>member name</th>
    <th>Chat with member personally</th>
    </tr>
    {% for user in room_detail.user.all %}

    <td>{{user.username}}</td>
    <td><button>chat</button></td>
    {% endfor %}
</table>
</div>
{% endif %}
 
  <div id="chats">
    </div>

{% endblock %}


{% block extra_body %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);
            var socket = new ReconnectingWebSocket(ws_path);

            // Handle incoming messages
            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);
                    console.log(data);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("button.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    socket.send(JSON.stringify({
                        "command": "leave",
                        "room": roomId
                    }));
                } else {
                    // Join room
                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));
                }
                
            });

            // Helpful debugging
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $('.confirm_btn').on ('click', function (){
        console.log("________________coming_______________");
        $.post("{% url 'chat:member_room_request' %}", {
            room_id: '{{ room.id }}',
            user_id: '{{ request.user.id }}',
            csrfmiddlewaretoken: '{{ csrf_token }}',
        },function(result, status){
                if (result.status == 'requested') {
                    $('.confirmation-btn').html('Your Request is Submited!');
                    $('.confirm_btn').hide();
                }
                });

    });


</script>
{% endblock %}

{% block scripts %}
{{ block.super }}

{% endblock %}

multichat/templates/rooms/rooms.html
{% extends "base.html" %}

{% block title %}Rooms{% endblock %}
{% block header_text %}Room List{% endblock %}

{% block content %}

<table class="table align-items-center table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Rooms Id</th>
        <th>Name</th>
        <th></th>
        <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    {% for room in rooms %}
        <tr>
            <td>{{room.id|stringformat:"03d"}}</td>
            <td>{{room.title|title}}</td>
            <td></td>
            <td class="text-center">
                <a href="{% url 'chat:room_detail' pk=room.id %}"><button>View Room</button></a>&nbsp;
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}