multichat/chat/urls.py
from django.urls import path
from chat import views

urlpatterns = [
    path('room/list/', views.Rooms.as_view(), name='room'),
    path('room/detail/<int:pk>/', views.RoomDetailView.as_view(),name='room_detail'),
    path('room/status/requeste/', views.MemberPAgeRequestAPIView.as_view(),
         name='member_room_request'
         ),
    path('room/chatting/', views.ChattingRooms.as_view(), name='room_chatting'),
    path('owner/dashboard/', views.OwnerDashboard.as_view(), name='owner_dashboard'),
    path('room/owner/<int:pk>/create/admin/page/', 
    	views.CreatePageAdminView.as_view(),name='create_room_admin'),
    path('room/admin/dashboard/', views.AdminDashboardView.as_view(),
    	 name='admin_dashboard'),
    path('room/admin/dashboard/', views.MemberPageRequestApproveAPIView.as_view(),
    	 name='member_request_approve'),





]

multichat/multichat/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from chat.views import IndexView
from common import views

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('accounts/login/', login),
    path('accounts/logout/', logout),
    path('admin/', admin.site.urls),
    path("register/", views.RegisterView.as_view(), name="register"),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),


]

multichat/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css" media="screen" />
	<script src="{% static "js/jquery-1.12.2.min.js" %}" type="text/javascript"></script>
	<script src="{% static "js/reconnecting-websocket.min.js" %}" type="text/javascript"></script>
	{% block extra_head %}{% endblock %}
</head>
<body>
	<header>
		<h1>{% block header_text %}{% endblock %}</h1>
		{% if user.is_authenticated %}
			<a href="/accounts/logout/">Logout</a>
		{% endif %}
	</header>
	<section>
		{% block content %}
		{% endblock %}
	</section>
	{% block extra_body %}{% endblock %}
</body>
</html>

multichat/templates/index.html
{% extends "base.html" %}

{% block title %}Rooms{% endblock %}
{% block header_text %}Room List{% endblock %}

{% block content %}

<a href="{% url 'chat:room' %}"><button>Chat Room List</button></a>
{% if request.user.user_profile.type == 'page_admin' %}
<a href="{% url 'chat:admin_dashboard' %}" ><button>Show My page</button></a>
{% endif %}
{% endblock %}